<?php
return [
    'fr' => [
        'nav_accueil' => 'Accueil',
        'nav_back' => 'BackOffice',
        'nav_front' => 'FrontOffice',
        'nav_saved' => 'Mes recettes enregistrées',
        'hero_title' => '✨ Manger malin, zéro gaspillage ✨',
        'hero_text' => 'Nutrivert — intelligence nutritionnelle & recettes durables dans le style de votre template test3.',
        'search_label' => 'Recherche par titre de recette',
        'search_placeholder' => 'Rechercher une recette',
        'search_btn' => 'Rechercher',
        'generate_recipe' => 'Générer recette',
        'recipe_day' => 'Recette du jour',
        'smart_suggestion' => 'Suggestion intelligente',
        'quick_recipes' => 'Recettes rapides',
        'goal_mode' => 'Mode objectif',
        'reset' => 'Réinitialiser',
        'choose_regime' => 'Choisir un régime (optionnel)',
        'all_regimes' => 'Tous les régimes',
        'choose_ingredients' => 'Choisir les ingrédients disponibles dans la base',
        'no_ingredients' => 'Aucun ingrédient trouvé dans la base. Ajoutez d’abord des recettes avec ingrédients dans le BackOffice.',
        'need_ingredient_generate' => 'Choisissez au moins un ingrédient avant de générer une recette. Le régime est optionnel.',
        'cancel' => 'Annuler',
        'smart_help' => 'Choisis les ingrédients que tu as. Le système affiche les recettes compatibles même partiellement, avec un pourcentage.',
        'show_suggestions' => 'Afficher suggestions',
        'choose_goal' => 'Choisir un objectif',
        'choose' => '-- Choisir --',
        'show_recipes' => 'Afficher recettes',
        'result_generate' => 'Résultat Générer recette',
        'result_search' => 'Recherche par titre',
        'result_fast_suffix' => 'recettes de 20 minutes ou moins.',
        'goal_chosen' => 'objectif choisi',
        'ingredients_chosen' => 'ingrédients choisis',
        'recipe' => 'Recette',
        'objective' => 'Objectif',
        'regime' => 'Régime',
        'duration' => 'Durée',
        'compatibility' => 'Compatibilité',
        'ingredients' => 'ingrédients',
        'view_details' => 'Voir détails',
        'save' => 'Enregistrer',
        'no_recipe_found' => 'Aucune recette trouvée.',
        'details_title' => 'Étapes et ingrédients',
        'quantity' => 'Quantité',
        'back_recipes' => 'Retour aux recettes',
        'saved_title' => 'Mes recettes enregistrées',
        'saved_text' => 'Voici les recettes que vous avez enregistrées depuis le FrontOffice.',
        'saved_badge' => 'Enregistrée',
        'delete' => 'Supprimer',
        'no_saved' => 'Aucune recette enregistrée pour le moment.',
        'see_recipes' => 'Voir les recettes',
        'confirmation' => 'Confirmation',
        'delete_confirm' => 'Voulez-vous vraiment supprimer cet élément ?',
        'confirm' => 'Confirmer',
        'dashboard_title' => 'Dashboard BackOffice',
        'dashboard_text' => 'Gestion complète des recettes dans un style visuel aligné sur test3.',
        'add_full' => 'Ajouter recette complète',
        'add_full_text' => 'Créer une recette avec plusieurs étapes dans la même page.',
        'edit_full' => 'Modifier recette complète',
        'edit_full_text' => 'Choisir une recette et modifier ou supprimer la recette avec ses instructions dans une seule page.',
        'lang_fr' => 'FR', 'lang_en' => 'EN', 'lang_ar' => 'AR',
        'js_need_suggestion' => 'Choisissez au moins un ingrédient pour la suggestion intelligente.',
        'js_need_goal' => 'Choisissez un objectif avant d’afficher les recettes.',
    ],
    'en' => [
        'nav_accueil' => 'Home', 'nav_back' => 'BackOffice', 'nav_front' => 'FrontOffice', 'nav_saved' => 'Saved recipes',
        'hero_title' => '✨ Eat smart, zero waste ✨',
        'hero_text' => 'Nutrivert — nutritional intelligence and sustainable recipes in the style of your test3 template.',
        'search_label' => 'Search by recipe title', 'search_placeholder' => 'Search for a recipe', 'search_btn' => 'Search',
        'generate_recipe' => 'Generate recipe', 'recipe_day' => 'Recipe of the day', 'smart_suggestion' => 'Smart suggestion', 'quick_recipes' => 'Quick recipes', 'goal_mode' => 'Goal mode', 'reset' => 'Reset',
        'choose_regime' => 'Choose a diet (optional)', 'all_regimes' => 'All diets', 'choose_ingredients' => 'Choose ingredients available in the database', 'no_ingredients' => 'No ingredient found in the database. First add recipes with ingredients in the BackOffice.',
        'need_ingredient_generate' => 'Choose at least one ingredient before generating a recipe. Diet is optional.', 'cancel' => 'Cancel',
        'smart_help' => 'Choose the ingredients you have. The system shows compatible recipes, even partially, with a percentage.', 'show_suggestions' => 'Show suggestions',
        'choose_goal' => 'Choose a goal', 'choose' => '-- Choose --', 'show_recipes' => 'Show recipes',
        'result_generate' => 'Generate recipe result', 'result_search' => 'Search by title', 'result_fast_suffix' => 'recipes of 20 minutes or less.', 'goal_chosen' => 'chosen goal', 'ingredients_chosen' => 'chosen ingredients',
        'recipe' => 'Recipe', 'objective' => 'Goal', 'regime' => 'Diet', 'duration' => 'Duration', 'compatibility' => 'Compatibility', 'ingredients' => 'ingredients',
        'view_details' => 'View details', 'save' => 'Save', 'no_recipe_found' => 'No recipe found.',
        'details_title' => 'Steps and ingredients', 'quantity' => 'Quantity', 'back_recipes' => 'Back to recipes',
        'saved_title' => 'Saved recipes', 'saved_text' => 'Here are the recipes you saved from the FrontOffice.', 'saved_badge' => 'Saved', 'delete' => 'Delete', 'no_saved' => 'No saved recipe yet.', 'see_recipes' => 'See recipes',
        'confirmation' => 'Confirmation', 'delete_confirm' => 'Do you really want to delete this item?', 'confirm' => 'Confirm',
        'dashboard_title' => 'BackOffice Dashboard', 'dashboard_text' => 'Complete recipe management with a visual style aligned with test3.', 'add_full' => 'Add complete recipe', 'add_full_text' => 'Create a recipe with several steps on the same page.', 'edit_full' => 'Edit complete recipe', 'edit_full_text' => 'Choose a recipe and edit or delete it with its instructions on one page.',
        'lang_fr' => 'FR', 'lang_en' => 'EN', 'lang_ar' => 'AR',
        'js_need_suggestion' => 'Choose at least one ingredient for the smart suggestion.', 'js_need_goal' => 'Choose a goal before showing recipes.',
    ],
    'ar' => [
        'nav_accueil' => 'الرئيسية', 'nav_back' => 'الإدارة', 'nav_front' => 'واجهة المستخدم', 'nav_saved' => 'وصفاتي المحفوظة',
        'hero_title' => '✨ كُل بذكاء، بدون تبذير ✨',
        'hero_text' => 'Nutrivert — ذكاء غذائي ووصفات مستدامة بنفس ستايل قالب test3.',
        'search_label' => 'البحث بعنوان الوصفة', 'search_placeholder' => 'ابحث عن وصفة', 'search_btn' => 'بحث',
        'generate_recipe' => 'إنشاء وصفة', 'recipe_day' => 'وصفة اليوم', 'smart_suggestion' => 'اقتراح ذكي', 'quick_recipes' => 'وصفات سريعة', 'goal_mode' => 'وضع الهدف', 'reset' => 'إعادة ضبط',
        'choose_regime' => 'اختر النظام الغذائي (اختياري)', 'all_regimes' => 'كل الأنظمة', 'choose_ingredients' => 'اختر المكونات الموجودة في قاعدة البيانات', 'no_ingredients' => 'لا توجد مكونات في قاعدة البيانات. أضف وصفات بمكونات من BackOffice أولاً.',
        'need_ingredient_generate' => 'اختر مكوّنًا واحدًا على الأقل قبل إنشاء وصفة. النظام الغذائي اختياري.', 'cancel' => 'إلغاء',
        'smart_help' => 'اختر المكونات المتوفرة لديك. النظام يعرض الوصفات المتوافقة حتى جزئيًا مع نسبة مئوية.', 'show_suggestions' => 'عرض الاقتراحات',
        'choose_goal' => 'اختر هدفًا', 'choose' => '-- اختر --', 'show_recipes' => 'عرض الوصفات',
        'result_generate' => 'نتيجة إنشاء الوصفة', 'result_search' => 'بحث حسب العنوان', 'result_fast_suffix' => 'وصفات مدتها 20 دقيقة أو أقل.', 'goal_chosen' => 'الهدف المختار', 'ingredients_chosen' => 'المكونات المختارة',
        'recipe' => 'وصفة', 'objective' => 'الهدف', 'regime' => 'النظام الغذائي', 'duration' => 'المدة', 'compatibility' => 'التوافق', 'ingredients' => 'مكونات',
        'view_details' => 'عرض التفاصيل', 'save' => 'حفظ', 'no_recipe_found' => 'لا توجد وصفات.',
        'details_title' => 'الخطوات والمكونات', 'quantity' => 'الكمية', 'back_recipes' => 'العودة للوصفات',
        'saved_title' => 'وصفاتي المحفوظة', 'saved_text' => 'هذه هي الوصفات التي حفظتها من FrontOffice.', 'saved_badge' => 'محفوظة', 'delete' => 'حذف', 'no_saved' => 'لا توجد وصفات محفوظة حاليًا.', 'see_recipes' => 'عرض الوصفات',
        'confirmation' => 'تأكيد', 'delete_confirm' => 'هل تريد حقًا حذف هذا العنصر؟', 'confirm' => 'تأكيد',
        'dashboard_title' => 'لوحة تحكم BackOffice', 'dashboard_text' => 'إدارة كاملة للوصفات بستايل قريب من test3.', 'add_full' => 'إضافة وصفة كاملة', 'add_full_text' => 'إنشاء وصفة بعدة خطوات في نفس الصفحة.', 'edit_full' => 'تعديل وصفة كاملة', 'edit_full_text' => 'اختيار وصفة وتعديلها أو حذفها مع تعليماتها في صفحة واحدة.',
        'lang_fr' => 'FR', 'lang_en' => 'EN', 'lang_ar' => 'AR',
        'js_need_suggestion' => 'اختر مكوّنًا واحدًا على الأقل للاقتراح الذكي.', 'js_need_goal' => 'اختر هدفًا قبل عرض الوصفات.',
    ],
];
